name: Pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --verbose

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    container: rust:1.71.0
    services:
      vault:
        image: vault:1.13.3
        env:
          VAULT_DEV_ROOT_TOKEN_ID: my-super-secret-token
    env:
      VAULT_ADDR: http://vault:8200
      VAULT_AUTH_METHOD: Token
      VAULT_TOKEN: my-super-secret-token
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --lib